name: CI

on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Select product'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - tas
          - ist
          - tasw
      step:
        description: 'Select step'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - build
          - upload
          - publish
jobs:
  unit-tests:
    container:
      image: pivotalcfreleng/golang

    timeout-minutes: 90
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        product: ["vsphere", "aws"]

    steps:
      - uses: actions/checkout@v2
      - id: run
        name: run it
        run: .github/tasks/test.sh
        env:
          PRODUCT: ${{ github.event.inputs.product }}
          STEP: ${{ github.event.inputs.step }}