name: CI

on:
  workflow_dispatch:
    inputs:
      publish-tas:
        description: 'Publish TAS'
        required: true
        type: boolean
      publish-ist:
        description: 'Publish IST'
        required: true
        type: boolean
      publish-tasw:
        description: 'Publish TASW'
        required: true
        type: boolean

      step:
        description: 'Select step'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - build
          - upload
          - publish
jobs:
  detect:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      products: ${{ steps.detect.outputs.products }}
      step: ${{ steps.detect.outputs.step }}
    steps:
      - uses: actions/checkout@v2
      - id: detect
        name: compute selections
        run: .github/tasks/test.sh
        env:
          PUBLISH_TAS: ${{ github.event.inputs.publish-tas }}
          PUBLISH_IST: ${{ github.event.inputs.publish-ist }}
          PUBLISH_TASW: ${{ github.event.inputs.publish-tasw }}
          STEP: ${{ github.event.inputs.step }}


  unit-tests:
    needs: [detect]
    container:
      image: pivotalcfreleng/golang

    timeout-minutes: 90
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        product: ${{ fromJson(needs.detect.outputs.products) }}

    steps:
      - uses: actions/checkout@v2
      - id: run
        name: run it
        run: .github/tasks/test.sh
        env:
          PRODUCT: ${{ github.event.inputs.product }}
          STEP: ${{ github.event.inputs.step }}